app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):
    name = StringField('Name', validators=[Required()])
    room = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm

@main.route('/', methods=['GET', 'POST'])
def index():
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
        
    return render_template('index.html', form=form)


@main.route('/chat')
def chat():
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))

    return render_template('chat.html', name=name, room=room)

app/templates/chat.html
<html>

<head>
  <title>Flask-SocketIO-Chat: {{ room }} </title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
  <script type="text/javascript" charset="utf-8">
    var socket;
    var username = '';
    $(document).ready(function () {
      socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
      socket.on('connect', function () {
        socket.emit('joined', {});
      });

      socket.on('status', function (data) {
        $('#chat_msgs').append(`
          <div>
            <span style="color:#555;">< ${data.msg } ></span>
          </div>
        `);
        $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
        $('#chat').scrollTop($('#chat')[0].scrollHeight);
      });

      socket.on('previousMessage', function (data) {
        for (index in data) {
          console.log(data[0]);
          $('#chat_msgs').append(
            `
          <div style="display:flex;
          justify-content: flex-start;">
          <div style="display:flex;flex-direction: column">
          ${index == 0 || data[index - 1].name != data[index].name ?
              `<strong class="get-username">${data[index].name}</strong>` : ''
            }
          
          <button 
            style="margin-bottom: 2px;" 
            type="button" 
            class="btn btn-primary"
          >${data[index].msg}</button>
          </div>
          </div>
        `
          );

        }
      })

      socket.on('message', function (data) {
        userText = `<strong class="get-username">${data.name}</strong>`

        $('#chat_msgs').append(
          `
          <div style="display:flex;justify-content: flex-start;">
          <div style="display:flex;flex-direction: column">
          ${userText}
          
          <button 
            style="margin-bottom: 2px; align-self: flex-end;" 
            type="button" 
            class="btn btn-primary"
          >${data.msg}</button>
          </div>
          </div>
        `
        );
      });
      $('#text').keypress(function (e) {
        var code = e.keyCode || e.which;
        if (code == 13) {
          text = $('#text').val();
          $('#text').val('');
          socket.emit('text', { msg: text });
        }
      });
    });
    function leave_room() {
      socket.emit('left', {}, function () {
        socket.disconnect();

        // go back to the login page
        window.location.href = "{{ url_for('main.index') }}";
      });
    }
  </script>
</head>

<body>
  <div style="background: #ccc; display: flex; flex:1; height: 100%; align-items: center; justify-content: center;">

    <div style="display: flex; flex:1;flex-direction: column; align-items: center;">
      <h1>Sala: {{ room }}</h1>
      <h5 id="username">User: {{name}} </h4>

        <div id="chat" class="card" style="width: 50%;">
          <div id="user_status"></div>
          <div id="chat_msgs" class="card-body" style="display: flex; flex-direction: column; ">
          </div>
          <input id="text" class="form-control" type="text" placeholder="Digite sua mensagem aqui"><br><br>
        </div>
        <div style="display: flex; width: 50%;">
          <a href="#" onclick="leave_room();">
            ◄ Sair da sala</a>
        </div>
    </div>
  </div>
</body>

</html>

app/templates/index.html
<html>
    <head>
        <title>Flask-SocketIO-Chat</title>
    </head>
    <body>
        <h1>Flask-SocketIO-Chat</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
    </body>
</html>